export interface MatchTeam {
  id: number;
  team: {
    id: number;
    sport_obj: {
      id: number;
      name: string;
      sport_code: string;
      is_team_sport: boolean;
      logo: string | null;
      capacity: number;
      is_active: boolean;
      sport_config: {
        quarters: number;
        referees: {
          goal_judges: number;
          timekeepers: number;
          main_referees: number;
        };
        ball_type: string;
        cap_colors: string[];
        shot_clock: number;
        venue_type: string;
        goal_throws: boolean;
        water_safety: boolean;
        corner_throws: boolean;
        exclusion_area: boolean;
        exclusion_time: number;
        match_duration: number;
        neutral_throws: boolean;
        penalty_throws: boolean;
        scoring_system: string;
        goal_dimensions: {
          width: number;
          height: number;
        };
        minimum_players: number;
        points_per_goal: number;
        pool_dimensions: {
          width: number;
          length: number;
          depth_min: number;
        };
        overtime_periods: boolean;
        players_per_team: number;
        quarter_duration: number;
        extra_time_duration: number;
        personal_foul_limit: number;
        substitution_windows: number;
        substitutions_allowed: number;
        swimming_pool_required: boolean;
      };
      brand: number;
    };
    name: string;
    displayname: string | null;
    description: string | null;
    formation: string | null;
    logo: string | null;
    is_active: boolean;
    fb_link: string | null;
    twitter_link: string | null;
    google_link: string | null;
    site_link: string | null;
    sport: number;
    venue: number | null;
    leagues: number[];
  };
  is_winner: boolean | null;
  score: number;
  penalties_shots: number;
  penalties_score: number;
  red_cards: number;
  yellow_cards: number;
  fouls: number;
  offsides: number;
  shots_off_target: number;
  corners: number;
  possession_percentage: number | null;
  shots_blocked: number;
  substitutions: number;
  injuries: number;
  formation: string | null;
  predictions_total: number | null;
  points: number;
  two_pointers_made: number;
  two_pointers_attempted: number;
  three_pointers_made: number;
  three_pointers_attempted: number;
  one_pointers_made: number;
  one_pointers_attempted: number;
  rebounds: number;
  offensive_rebounds: number;
  defensive_rebounds: number;
  assists: number;
  steals: number;
  blocks: number;
  turnovers: number;
  personal_fouls: number;
  two_point_percentage: number | null;
  three_point_percentage: number | null;
  one_point_percentage: number | null;
  goals: number;
  saves: number;
  exclusions: number;
  penalty_goals: number;
  power_play_goals: number;
  shots_attempted: number;
  shots_on_target: number;
  exclusion_time: number;
  major_fouls: number;
  minor_fouls: number;
  shot_accuracy: number | null;
  difficulty_score: number | null;
  execution_score: number | null;
  combined_score: number | null;
  deductions: number | null;
  falls: number;
  routines_completed: number;
  total_routines: number;
  artistic_score: number | null;
  technical_score: number | null;
  apparatus_scores: Record<string, any>;
  previous_stats: {
    fouls: number;
    score: number;
    corners: number;
    offsides: number;
    red_cards: number;
    yellow_cards: number;
    penalties_score: number;
    penalties_shots: number;
    shots_on_target: number;
  };
  created_at: string | null;
  updated_at: string | null;
  is_active: boolean;
  match: number;
}