export interface SportConfig {
  quarters: number;
  referees: {
    goal_judges: number;
    timekeepers: number;
    main_referees: number;
  };
  ball_type: string;
  cap_colors: string[];
  shot_clock: number;
  venue_type: string;
  goal_throws: boolean;
  water_safety: boolean;
  corner_throws: boolean;
  exclusion_area: boolean;
  exclusion_time: number;
  match_duration: number;
  neutral_throws: boolean;
  penalty_throws: boolean;
  scoring_system: string;
  goal_dimensions: {
    width: number;
    height: number;
  };
  minimum_players: number;
  points_per_goal: number;
  pool_dimensions: {
    width: number;
    length: number;
    depth_min: number;
  };
  overtime_periods: boolean;
  players_per_team: number;
  quarter_duration: number;
  extra_time_duration: number;
  personal_foul_limit: number;
  substitution_windows: number;
  substitutions_allowed: number;
  swimming_pool_required: boolean;
}

export interface Sport {
  id: number;
  name: string;
  sport_code: string;
  is_team_sport: boolean;
  logo: string | null;
  capacity: number;
  is_active: boolean;
  sport_config: SportConfig;
  brand: number;
}

export interface Team {
  id: number;
  sport_obj: Sport;
  name: string;
  displayname: string | null;
  description: string | null;
  formation: string | null;
  logo: string | null;
  is_active: boolean;
  fb_link: string | null;
  twitter_link: string | null;
  google_link: string | null;
  site_link: string | null;
  sport: number;
  venue: number | null;
  leagues: number[];
}

export interface Player {
  id: number;
  team_obj: Team;
  first_name: string;
  last_name: string;
  avatar: string | null;
  displayid: number;
  uniform: number;
  position: string;
  height: number;
  weight: number;
  birthdate: string | null;
  is_primary: boolean;
  goals: number | null;
  yellow_cards: number | null;
  red_cards: number | null;
  points: number | null;
  two_pointers_made: number | null;
  two_pointers_attempted: number | null;
  three_pointers_made: number | null;
  three_pointers_attempted: number | null;
  one_pointers_made: number | null;
  one_pointers_attempted: number | null;
  rebounds: number | null;
  offensive_rebounds: number | null;
  defensive_rebounds: number | null;
  assists: number | null;
  steals: number | null;
  blocks: number | null;
  turnovers: number | null;
  personal_fouls: number | null;
  minutes_played: number | null;
  two_point_percentage: number | null;
  three_point_percentage: number | null;
  one_point_percentage: number | null;
  saves: number | null;
  exclusions: number | null;
  penalty_goals: number | null;
  power_play_goals: number | null;
  swimming_distance: number | null;
  shots_attempted: number | null;
  shots_on_target: number | null;
  shot_accuracy: number | null;
  exclusion_time: number | null;
  major_fouls: number | null;
  minor_fouls: number | null;
  difficulty_score: number | null;
  execution_score: number | null;
  total_score: number | null;
  deductions: number | null;
  fall_count: number | null;
  routine_completion: number | null;
  artistic_score: number | null;
  technical_score: number | null;
  landing_quality: number | null;
  apparatus_specialty: string | null;
  competition_level: string | null;
  fb_link: string | null;
  twitter_link: string | null;
  google_link: string | null;
  site_link: string | null;
  games_played: number;
  created_at: string | null;
  updated_at: string | null;
  is_active: boolean;
  team: number;
  sport: number;
}

export interface MatchPlayer {
  id: number;
  player: Player;
  is_winner: boolean | null;
  score: number | null;
  predictions_total: number | null;
  red_cards: number;
  yellow_cards: number;
  goals: number;
  points: number;
  fouls: number;
  minutes_played: number;
  two_pointers_made: number;
  two_pointers_attempted: number;
  three_pointers_made: number;
  three_pointers_attempted: number;
  one_pointers_made: number;
  one_pointers_attempted: number;
  rebounds: number;
  offensive_rebounds: number;
  defensive_rebounds: number;
  assists: number;
  steals: number;
  blocks: number;
  turnovers: number;
  personal_fouls: number;
  two_point_percentage: number | null;
  three_point_percentage: number | null;
  one_point_percentage: number | null;
  saves: number;
  exclusions: number;
  penalty_goals: number;
  power_play_goals: number;
  shots_attempted: number;
  shots_on_target: number;
  shot_accuracy: number | null;
  exclusion_time: number;
  major_fouls: number;
  minor_fouls: number;
  swimming_distance: number | null;
  difficulty_score: number | null;
  execution_score: number | null;
  total_score: number | null;
  deductions: number | null;
  fall_count: number;
  routine_completion: number | null;
  artistic_score: number | null;
  technical_score: number | null;
  landing_quality: number | null;
  apparatus_performed: string | null;
  routine_duration: number;
  apparatus_scores: Record<string, any>;
  previous_stats: Record<string, any>;
  created_at: string | null;
  updated_at: string | null;
  match: number;
}